const routes = {
  managementPanel: { to: '/dashboard/', title: 'Панель управления' },
  main: { to: '/', title: 'Главная' },
  catalog: { to: '/catalog', title: 'Каталог' },
  catalogCategory: { to: '/catalog/:cat', title: 'Категория' },
  product: { to: '/catalog/:cat/:id', title: 'Товар' },
  about: { to: '/about', title: 'О нас' },
  agreement: { to: '/agreement', title: 'Пользовательское соглашение' },
  delivery_payment: { to: '/delivery-payment', title: 'Доставка и Оплата' },
  contact: { to: '/contact', title: 'Контакты' },
  warranty: { to: '/warranty', title: 'Гарантия' },
  partnership_invite: { to: '/partnership-invite', title: 'Приглашаем к сотрудничеству' },
  partnership_suppliers: { to: '/partnership-suppliers', title: 'Для постащиков' },
  return_exchange: { to: '/return-exchange', title: 'Возврат и обмен' },
  privacy: { to: '/privacy', title: 'Политика конфиденциальности' },
  terms: { to: '/terms', title: 'Правила пользования сайтом' },
  wholesale: { to: '/wholesale', title: 'Оптовикам' },
  profile: { to: '/profile', title: 'Профиль' },
  orders: { to: '/orders', title: 'История заказов' },
  order: { to: '/order/:id', title: 'Заказ' },
  orderPay: { to: '/order/:id/pay', title: 'Оплата заказа' },
  addresses: { to: '/addresses', title: 'Адреса доставки' },
  address: { to: '/address/:id', title: 'Адрес доставки' },
  wishlist: { to: '/wishlist', title: 'Список желаний' },
  cart: { to: '/cart', title: 'Корзина' },
  checkout: { to: '/checkout', title: 'Оформление заказа' },
  login: { to: '/login', title: 'Аккаунт' },
  register: { to: '/register', title: 'Регистрация' },
  registerVerify: {
    to: '/register-verify',
    title: 'Подтверждение регистрации',
  },
  passwordReset: { to: '/password-reset', title: 'Восстановление пароля' },
  passwordResetVerify: {
    to: '/password-reset/verify',
    title: 'Восстановление пароля',
  },
};

export default routes;
